/*

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

*/


public class Main {
    public static void main(String []args) {
        final int MAX = 500;
        long n = find(MAX);
        System.out.println("Answer " + n * (n + 1)/2);
    }

    public static long find(long n) {
        int i;
        int val;
        for(i = 2; true; i++) {
            val = nDivisors((int)i * (i + 1)/2);

            if(val >= n)
                return i;
        }
    }

    public static int nDivisors(int n) {
        int i;
        int c = 0;

        for(i = 2; i <= n / 2; i ++) {
            if(n % i == 0)
                c++;
        }

        return c + 2;
    }

}






